#!/bin/sh

# 1. Запускаем твой скрипт в ФОНЕ (знак & обязателен!)
/home/yaso/river-my-layout/my-layout &
riverctl default-layout yaso-layout
# riverctl rule-add -app-id '*' csd // -> window decoration

# --- БИНДЫ ---

riverctl map normal Super Return spawn foot
riverctl map normal Super Q close
riverctl map normal Super+Shift E exit
riverctl map normal Super F toggle-fullscreen

riverctl map-pointer normal Super BTN_RIGHT resize-view
riverctl map-pointer normal Super BTN_LEFT move-view
# --- ТВОИ БИНДЫ ДЛЯ СЛОЕВ ---

# Super + Space переключает между Stack и Tiling

riverctl map normal Super Space send-layout-cmd yaso-layout "toggle"

# Режим Stack: переключаем раскладку, включаем CSD (для новых окон) и убираем рамки River (сразу для всех)
riverctl map normal Super S spawn "sh -c 'riverctl send-layout-cmd yaso-layout stack; riverctl rule-del ssd; riverctl rule-add csd; riverctl border-width 0'"

# Режимы Tiling/Dwindle/Niri: переключаем раскладку, включаем SSD (рамки) и возвращаем границу в 2 пикселя
riverctl map normal Super C spawn "sh -c 'riverctl send-layout-cmd yaso-layout dwindle; riverctl rule-del csd; riverctl rule-add ssd; riverctl border-width 2'"
riverctl map normal Super N spawn "sh -c 'riverctl send-layout-cmd yaso-layout niri; riverctl rule-del csd; riverctl rule-add ssd; riverctl border-width 2'"

# Скролл вправо: фокус на окно правее (которое новее) + сдвиг раскладки
riverctl map normal Super Right spawn "sh -c 'riverctl focus-view previous; riverctl send-layout-cmd yaso-layout scroll-right'"

# Скролл влево: фокус на окно левее (которое старее) + сдвиг раскладки
riverctl map normal Super Left spawn "sh -c 'riverctl focus-view next; riverctl send-layout-cmd yaso-layout scroll-left'"



# Изменение размера тайлинга (двигаем границу)
riverctl map normal Super H send-layout-cmd yaso-layout "ratio-dec"
riverctl map normal Super L send-layout-cmd yaso-layout "ratio-inc"

# --- РАБОТА С ДВУМЯ МОНИТОРАМИ ---
# Переместить активное окно на следующий/предыдущий монитор
riverctl map normal Super+Shift Right send-to-output -current-tags HDMI-A-1
riverctl map normal Super+Shift Left send-to-output -current-tags DP-1

# Переключить фокус на другой монитор
riverctl map normal Super+Control Right focus-output HDMI-A-1
riverctl map normal Super+Control Left focus-output DP-1

riverctl border-color-focused 0x89b4fa
riverctl border-color-unfocused 0x45475a
riverctl border-color-urgent 0xf38ba8
riverctl border-width 2



# Переключение тегов Super+1-9
for i in $(seq 1 9); do
    tags=$((1 << ($i - 1)))
    riverctl map normal Super $i set-focused-tags $tags
    riverctl map normal Super+Shift $i set-view-tags $tags
done

wlr-randr --output DP-1 --mode 1366x768 --pos 0,0

# Настраиваем правый монитор (основной), сдвигая его вправо на 1366 пикселей
wlr-randr --output HDMI-A-1 --mode 1920x1080 --pos 1366,0

