#!/bin/sh

# 1. Запускаем твой скрипт в ФОНЕ (знак & обязателен!)
/home/yaso/river-my-layout/my-layout &

# 2. Устанавливаем твой генератор слоев
riverctl default-layout yaso-layout

# --- БИНДЫ ---

riverctl map normal Super Return spawn foot

riverctl map normal Super Q close

riverctl map normal Super+Shift E exit

riverctl map normal Super F toggle-fullscreen

riverctl map-pointer normal Super BTN_RIGHT resize-view
riverctl map-pointer normal Super BTN_LEFT move-view
# --- ТВОИ БИНДЫ ДЛЯ СЛОЕВ ---

# Super + Space переключает между Stack и Tiling

riverctl map normal Super Space send-layout-cmd yaso-layout "toggle"
riverctl map normal Super T send-layout-cmd yaso-layout "tiling"
riverctl map normal Super S send-layout-cmd yaso-layout "stack"

# Изменение размера тайлинга (двигаем границу)
riverctl map normal Super H send-layout-cmd yaso-layout "ratio-dec"
riverctl map normal Super L send-layout-cmd yaso-layout "ratio-inc"

# Переключение тегов Super+1-9
for i in $(seq 1 9); do
    tags=$((1 << ($i - 1)))
    riverctl map normal Super $i set-focused-tags $tags
    riverctl map normal Super+Shift $i set-view-tags $tags
done
